### ISSUE TITLE
change matrix.f to include the choice of helicity/color within that file.

### ISSUE THREAD

**Issue by oliviermattelaer** [oliviermattelaer/mg5amc_test#24]
# Idea
update the fortran code to have the same interface as for GPU and therefore avoid to put the JAMP2 in a common block 
 -  avoid to have to transfer it from GPU to CPU
 - good time to test the low memory selection of color to avoid to have all  jamp2 in memory at the same time (see #17)
 
# Todo:
 - [x] change signature of smatrix 
    - [x]  without helicity recycling
             - [ ] pass to the low memory mode (see #17) 
    - [x] wih helicity recycling
             - [ ] check if relevant to use the low memory mode (see #17) 
 - [ ] ~~change the signature of matrix~~
    - [ ]  ~~without helicity recycling~~
 - [x] change addmothers.f
 - [x] change the events writing 
    - [x] temporary format (avoid the use of buffer)
    - [x] final format

**Comment by oliviermattelaer** [comment]
note 
```
    CHARACTER*101         HEL_BUFF
    COMMON/TO_HELICITY/  HEL_BUFF
 WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL)
```
(need to be replaced via the call to ihel)
-> need to have a function get_helicity(iproc, ihel)
call get_helicity(iproc, ihel, nhel)
that calls get_nhelX(...)

**Comment by oliviermattelaer** [comment]
case without plugin/helicity recycling/mlm
implemented here:

https://github.com/mg5amcnlo/mg5amcnlo/commit/0587cbbd549c053414beb4ecf0b5883047a1a9a4
following commit is make the change consistent with helicity recycling
https://github.com/mg5amcnlo/mg5amcnlo/commit/18a90f58587e3a7b07610b9ed5780695d094a76c

**Comment by oliviermattelaer** [comment]
Validation:
- [x] check that the code compile
- [x] check that the cross-section is correct
- [x] Helicity
   - [x] are filled
       - [x] returned non zero from smatrix 
       - [x] are passed non zero (and same as smatrix) to write_leshouches
       - [x] are returning non zero from the new function for getting the helicity
          - function return 0 0 0 0 in last commit 
   - [x] have  correct rate 
      - wrong with helicity recycling since the index is remapped to not have "hole"  (fixed in https://github.com/mg5amcnlo/mg5amcnlo/commit/3622a74e42e00d97d4877f1b5985754e40baf2d1)
- [x] Color 
  - [x] are filled
  - [x] have correct rate   
- [x] JAMP2 
  - [x] check that all jamp2 have been removed from memory (especially the vectorised version)
